steps:
  - name: golang
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t',
            'gcr.io/imre-build-test/text-to-speech-demo:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/imre-build-test/text-to-speech-demo:$SHORT_SHA']
#   deploy to cloud run in staging
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'text-to-speech-stg', '--image', 'gcr.io/imre-build-test/text-to-speech-demo:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']