steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'text-to-speech-prod', '--image', 'gcr.io/imre-build-test/text-to-speech-demo:$SHORT_SHA',
           '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']